on: [push]

name: Test the 'hex-text' library

jobs:
    build:
        name: Test
        runs-on: ${{ matrix.os }}

        strategy:
            matrix:
                os: [ubuntu-latest, windows-latest, macos-latest]
                ghc: ['9.0.1', '8.10.3', '8.8.4', '8.6.5', '8.4.3', '8.2.2', '8.0.2']

        steps:
            - uses: actions/checkout@v2

            - name: Install Haskell
              id: install-haskell
              uses: haskell/actions/setup@v1
              with:
                  ghc-version: ${{ matrix.ghc }}

            - name: Cache Haskell dependencies
              uses: actions/cache@v2
              with:
                  key: ${{ runner.os }}-${{ matrix.ghc }}-${{ hashFiles('.github/workflows/test/test.hs') }}
                  restore-keys: |
                      ${{ runner.os }}-${{ matrix.ghc }}-
                      ${{ runner.os }}-
                  path: |
                      ${{ steps.install-haskell.outputs.cabal-store }}

            - name: Build the test runner
              run: |
                  cd .github/workflows/test
                  cabal install --install-method=copy --installdir=.

            - name: Test 'hex-text'
              run: |
                  cd hex-text
                  ../.github/workflows/test/test
              env:
                  ghc: ${{ matrix.ghc }}
